In [1]:
from google.colab import files
uploaded = files.upload()

Saving train_data.csv to train_data.csv


In [2]:
import pandas as pd

In [3]:
df_train = pd.read_csv('train_data.csv')

In [4]:
df_train = df_train[['Text data','Label']]

In [5]:
df_train.head(5)

,Text data,Label
0,Waiting for my mind to have a breakdown once t...,moderate
1,My new years resolution : I'm gonna get my ass...,moderate
2,New year : Somone else Feeling like 2020 will ...,moderate
3,"My story I guess : Hi, Im from Germany and my ...",moderate
4,Sat in the dark and cried myself going into th...,moderate


In [6]:
df_train.Label.unique()

array(['moderate', 'not depression', 'severe'], dtype=object)

In [7]:
type(df_train)

pandas.core.frame.DataFrame

In [8]:
print(df_train['Label'].value_counts())

moderate          3678
not depression    2755
severe             768
Name: Label, dtype: int64


In [9]:
df_train.isnull().sum()

Text data    0
Label        0
dtype: int64

In [10]:
df_train.describe()

,Text data,Label
count,7201,7201
unique,7006,3
top,im tired : i feel really shitty for being clin...,moderate
freq,2,3678


In [11]:
!pip install simpletransformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.7/250.7 kB 19.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 99.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.6/474.6 kB 45.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 5.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 114.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 78.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 81.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 89.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 27.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 20.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.5/206.5 kB 2

In [12]:
!pip install clean-text

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.4/175.4 kB 17.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 7.1 MB/s eta 0:00:00
  Created wheel for emoji: filename=emoji-1.7.0-py3-none-any.whl size=171033 sha256=3ba237c3c36bcfb9c2c411a29cac4cfe04e3c217cc5ce52df077fc88b0fec367
  Stored in directory: /root/.cache/pip/wheels/31/8a/8c/315c9e5d7773f74b33d5ed33f075b49c6eaeb7cedbb86e2cf8
Successfully built emoji


In [13]:
import nltk
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')
import re

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [14]:
def preprocess(sentence):
  sentence=str(sentence)
  sentence=sentence.lower()
  cleanr=re.compile('<.*?>')
  cleantext=re.sub(cleanr,'',sentence)
  rem_url=re.sub(r'http\S+','',cleantext)
  rem_num=re.sub('[0-9]+','',rem_url)
  rem_tag=re.sub(r'@\S+','',rem_num)
  tokenizer=RegexpTokenizer(r'\w+')
  tokens=tokenizer.tokenize(rem_tag)
  filtered_words=[w for w in tokens if len(w)>0 if not w in stopwords.words('english')]
  return " ".join(tokens)

df_train['Text data']=df_train['Text data'].map(lambda s:preprocess(s))
df_train.head(20)

,Text data,Label
0,waiting for my mind to have a breakdown once t...,moderate
1,my new years resolution i m gonna get my ass i...,moderate
2,new year somone else feeling like will be ther...,moderate
3,my story i guess hi im from germany and my eng...,moderate
4,sat in the dark and cried myself going into th...,moderate
5,i will probably end it when my mum isn t aroun...,moderate
6,fuck left abusive relationship moved in with a...,moderate
7,i am at a new year s eve party and i want to c...,moderate
8,death of my father my father died in the begin...,moderate
9,empty and stuck in a loop every day in any ord...,moderate


In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_train.Label = le.fit_transform(df_train.Label)
df_train.head(20)

,Text data,Label
0,waiting for my mind to have a breakdown once t...,0
1,my new years resolution i m gonna get my ass i...,0
2,new year somone else feeling like will be ther...,0
3,my story i guess hi im from germany and my eng...,0
4,sat in the dark and cried myself going into th...,0
5,i will probably end it when my mum isn t aroun...,0
6,fuck left abusive relationship moved in with a...,0
7,i am at a new year s eve party and i want to c...,0
8,death of my father my father died in the begin...,0
9,empty and stuck in a loop every day in any ord...,0


In [16]:
from simpletransformers.classification import ClassificationModel

In [17]:
model = ClassificationModel('albert', 'albert-base-v2', num_labels=3, use_cuda= True, args={
    "reprocess_input_data": True,
    "use_cached_eval_features": False,
    "overwrite_output_dir": True,
    "num_train_epochs": 1
})


Some weights of the model checkpoint at albert-base-v2 were not used when initializing AlbertForSequenceClassification: ['predictions.dense.weight', 'predictions.bias', 'predictions.LayerNorm.bias', 'predictions.LayerNorm.weight', 'predictions.dense.bias', 'predictions.decoder.bias', 'predictions.decoder.weight']
- This IS expected if you are initializing AlbertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing AlbertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of AlbertForSequenceClassification were not initialized from the model checkpoint at albert-base-v2 and are newly initialized: ['classifier.weight', 'classifier.bias']
You sho

In [18]:
model.train_model(df_train)

/usr/local/lib/python3.10/dist-packages/simpletransformers/classification/classification_model.py:612: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  warnings.warn(


  0%|          | 0/7201 [00:00<?, ?it/s]

Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 0 of 1:   0%|          | 0/901 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py:139: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "


(901, 0.9293299769190916)

DEVELOPMENT DATA

In [19]:
from google.colab import files
uploaded = files.upload()

Saving dev_data.csv to dev_data.csv


In [20]:
df_eval = pd.read_csv('dev_data.csv')
df_eval = df_eval[['textdata','Classlabels']]
df_eval

,textdata,Classlabels
0,Im scared : This is it. I lie to myself every ...,moderate
1,New to this but just wanted to vent : I just f...,moderate
2,I’m sad : It’s kinda always been an issue. I w...,moderate
3,Lonely but not alone. : All of my immediately ...,moderate
4,This year has been trash. : I dont know why I’...,moderate
...,...,...
3240,"Feeling lonely. : Hi reddit, I haven’t posted ...",severe
3241,When would suicide be right? : So I got back f...,severe
3242,Lowest I’ve ever been ever. : To make a long s...,severe
3243,Does the Toxoplasma Gondii ruined my life ? (f...,severe


In [21]:
df_eval['textdata']=df_eval['textdata'].map(lambda s:preprocess(s))
df_eval.head(20)

,textdata,Classlabels
0,im scared this is it i lie to myself every day...,moderate
1,new to this but just wanted to vent i just fin...,moderate
2,i m sad it s kinda always been an issue i woul...,moderate
3,lonely but not alone all of my immediately fam...,moderate
4,this year has been trash i dont know why i m p...,moderate
5,needed to yell into the void i m a pos i m cur...,moderate
6,i don t know why i m here anymore i feel like ...,moderate
7,i dont want to be here anymore i dont wanna di...,moderate
8,antidepressants do antidepressants help if you...,moderate
9,tms my doctor wants me to do tms for my depres...,moderate


In [22]:
df_eval['textdata']

0       im scared this is it i lie to myself every day...
1       new to this but just wanted to vent i just fin...
2       i m sad it s kinda always been an issue i woul...
3       lonely but not alone all of my immediately fam...
4       this year has been trash i dont know why i m p...
                              ...                        
3240    feeling lonely hi reddit i haven t posted to t...
3241    when would suicide be right so i got back from...
3242    lowest i ve ever been ever to make a long stor...
3243    does the toxoplasma gondii ruined my life firs...
3244    getting the correct diagnosis currently going ...
Name: textdata, Length: 3245, dtype: object

In [23]:
le = LabelEncoder()
df_eval.Classlabels = le.fit_transform(df_eval.Classlabels)
df_eval.head(20)

,textdata,Classlabels
0,im scared this is it i lie to myself every day...,0
1,new to this but just wanted to vent i just fin...,0
2,i m sad it s kinda always been an issue i woul...,0
3,lonely but not alone all of my immediately fam...,0
4,this year has been trash i dont know why i m p...,0
5,needed to yell into the void i m a pos i m cur...,0
6,i don t know why i m here anymore i feel like ...,0
7,i dont want to be here anymore i dont wanna di...,0
8,antidepressants do antidepressants help if you...,0
9,tms my doctor wants me to do tms for my depres...,0


In [61]:

df_eval.tail(20)

,textdata,Classlabels
3225,first day taking venlafaxine so my doctor has ...,2
3226,medication is not helping my doctor diagnosed ...,2
3227,scars and sex im a year old dude that still se...,2
3228,mass shooting in germany hey my name is thomas...,2
3229,still waiting on my psychiatrist appointment r...,2
3230,i m losing it i ve been struggling with ptsd a...,2
3231,too broken to change what matters i m depresse...,2
3232,today i opened up to my friends and it was a m...,2
3233,fluoxetine to pristiq question hey i m switchi...,2
3234,d a f depressed as fuck i ve been diagnosed wi...,2


In [24]:
result, model_outputs, wrong_predictions = model.eval_model(df_eval)

/usr/local/lib/python3.10/dist-packages/simpletransformers/classification/classification_model.py:1454: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  warnings.warn(


  0%|          | 0/3245 [00:00<?, ?it/s]

Running Evaluation:   0%|          | 0/406 [00:00<?, ?it/s]

In [25]:
print(model_outputs)

[[ 0.96679688 -0.30249023 -0.671875  ]
 [ 0.64550781 -0.01382446 -0.81591797]
 [ 0.57128906 -0.10272217 -0.68261719]
 ...
 [ 0.60644531 -0.13256836 -0.69140625]
 [ 0.53515625  0.22949219 -1.07910156]
 [ 0.44726562  0.03793335 -0.79052734]]


In [26]:
print(result)

{'mcc': 0.14710202416128623, 'eval_loss': 0.8503681201065703}


In [27]:
print(model.predict(["Thank you, that really helps. Now I feel ten times worse."]))

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

(array([1]), array([[ 0.11029053,  0.66650391, -1.51757812]]))


In [28]:
print(len(wrong_predictions))

1315


In [29]:
print(wrong_predictions[6])

{'guid': 34, 'text_a': 'even eating has become a chore everything is exhausting and meaningless i just want to lie down in darkness close my eyes and never open them again', 'text_b': None, 'label': 0}


In [30]:
predictions, raw_outputs = model.predict(df_eval['textdata'].tolist())
print(predictions)
print(raw_outputs)

  0%|          | 0/3245 [00:00<?, ?it/s]

  0%|          | 0/406 [00:00<?, ?it/s]

[0 0 0 ... 0 0 0]
[[ 0.96679688 -0.30249023 -0.671875  ]
 [ 0.64550781 -0.01382446 -0.81591797]
 [ 0.57128906 -0.10272217 -0.68261719]
 ...
 [ 0.60644531 -0.13256836 -0.69140625]
 [ 0.53515625  0.22949219 -1.07910156]
 [ 0.44726562  0.03793335 -0.79052734]]


In [31]:
print(predictions)

[0 0 0 ... 0 0 0]


In [32]:
print(len(predictions))

3245


In [33]:
from sklearn.metrics import classification_report
print(classification_report(df_eval.Classlabels,predictions))

              precision    recall  f1-score   support

           0       0.71      0.69      0.70      2169
           1       0.38      0.51      0.43       848
           2       0.00      0.00      0.00       228

    accuracy                           0.59      3245
   macro avg       0.36      0.40      0.38      3245
weighted avg       0.57      0.59      0.58      3245



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [34]:
print(wrong_predictions)

[{'guid': 8, 'text_a': 'antidepressants do antidepressants help if your not depressed i started taking them to get through a rough patch and they have helped me does this mean i technically have depression because i read online that antidepressants don t help if your not depressed', 'text_b': None, 'label': 0}, {'guid': 9, 'text_a': 'tms my doctor wants me to do tms for my depression has anyone done tms or is doing it i was just want to know it is worth it', 'text_b': None, 'label': 0}, {'guid': 19, 'text_a': 'hope is a drug i do not care what anyone says hope is the most addicting substance there is it s a drug that pumps up your mind and gives you a smile you think is real until it s taken away and it hurts so much your body goes through withdrawals', 'text_b': None, 'label': 0}, {'guid': 21, 'text_a': 'happy people piss me off i don t know why but when i see people that are so care free and happy i just get mad like they re taunting me or something saying hey i m happier than you lo

In [35]:
not_depressed = 0
moderate = 0
depressed = 0

for x in wrong_predictions:
    if x.label == 0:
        not_depressed += 1
    elif x.label == 1:
        moderate += 1
    elif x.label == 2:
        depressed += 1

print("Not Depressed:", not_depressed)
print("Moderate:", moderate)
print("Depressed:", depressed)


Not Depressed: 668
Moderate: 419
Depressed: 228


In [39]:
from google.colab import files
uploaded = files.upload()

Saving test_data.csv to test_data.csv


In [42]:
import pandas as pd

# Read the CSV file and select the desired column
df = pd.read_csv('test_data.csv')
selected_column = df['Textdata']

# Make predictions on the selected column
predictions = model.predict(selected_column.tolist())

# Print the predictions
print(predictions)


  0%|          | 0/499 [00:00<?, ?it/s]

  0%|          | 0/63 [00:00<?, ?it/s]

(array([0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0

In [70]:
from sklearn.metrics import accuracy_score

actual_labels = df_eval['Classlabels']
predicted_labels = predictions

accuracy = accuracy_score(actual_labels, predicted_labels)
accuracy_percentage = accuracy * 100

print("Accuracy: {:.2f}%".format(accuracy_percentage))


ValueError: ignored

In [49]:
prediction_array = predictions[0]
print(prediction_array)


[0 1 1 1 0 1 0 1 1 1 1 0 1 1 1 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 1
 0 1 0 0 1 1 0 0 1 0 1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1
 1 0 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 1 0 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0
 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 1
 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0
 0 0 1 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 1 0 0 0 1
 0 0 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0
 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0
 1 0 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 0
 1 1 0 0 0 0 1 0 0 0 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 1 0 1 0 1 1 0 1 1 0 1 0 0 1 0 0 0 0 0 1
 0 0 0 0 1 0 0 0 0 0 0 0 

In [60]:
import csv


# Open the existing CSV file
with open('test_data.csv', 'r') as file:
    reader = csv.reader(file)
    rows = list(reader)

# Add a new column header for the prediction values
header = rows[0]
header.append('Prediction')

# Add values to the new column
for i in range(1, len(rows)):
    if i - 1 < len(prediction_array):
        rows[i].append(prediction_array[i - 1])
    else:
        rows[i].append(None)

# Write the updated data to a new CSV file
with open('updated_test4.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(rows)


In [68]:
import pandas as pd

# Read the updated CSV file
df_updated = pd.read_csv('updated_test4.csv')

# Print the head 20 rows
print(df_updated.head(20))


           Pid                                           Textdata  Prediction
0    test_id_1  This is me. Don?? get me wrong, it?? better th...           0
1    test_id_2  I hate that people don?? understand that i don...           1
2    test_id_3  But here I am, 24 years old man and doing exac...           1
3    test_id_4  I?? trapped inside. Does anyone else get that ...           1
4    test_id_5  I read a lot of posts on here of people strugg...           0
5    test_id_6  Thank you, that really helps. Now I feel ten t...           1
6    test_id_7  I don?? know if that makes sense. What I mean ...           0
7    test_id_8  Does anyone else feel this way? This has been ...           1
8    test_id_9    The first 6 words of the title is accurate too.           1
9   test_id_10                                            Fuck ??           1
10  test_id_11  Just curious if anyone else affected by this p...           1
11  test_id_12  She was only 67. She told me every so often ab..

In [63]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [64]:
!pip install huggingface_hub

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
